### ISSUE TITLE
The requested URL returned error: 403

### ISSUE THREAD

**Issue by zxcbbn** [zxcbbn/omooc.py#1]
@yzha3917
@dudutang
@zxcbbn
@xiaokechenchen
@cp4
@TonyYet
# The requested URL returned error: 403
## 问题出现过程与尝试

**设置 GitHub GitBook 双推**
 按照群里的 [gitbook 双推技巧](https://github.com/OpenMindClub/OMOOC.py/wiki/gitbook_double_push)       设置 git push -u origin master 后出现群中 [git_push_confilct](https://github.com/OpenMindClub/OMOOC.py/wiki/git_push_confilct)提到的问题
先尝试git pull

<pre><code> fatal: unable to access 'https://git.gitbook.com/zxcbbn/pythoncamp0.git/': The requested URL returned error: 403
</code></pre>

后尝试 [git_push_confilct](https://github.com/OpenMindClub/OMOOC.py/wiki/git_push_confilct) 的 git push -u gitbook +master 未出现文中所说

> push至gitbook时，需要输入gitbook的用户名与密码。用户名与密码在gitbook账户的Profile-Username、Password里面查看与设置。

<pre><code>fatal: 'gitbook' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
</code></pre>

**在 GitHub 中搜索问题**
按照 [GitHub 帮助](https://help.github.com/articles/https-cloning-errors/)

并未出现文中提到的

> When prompted for a username and password, make sure you use an account that has access to the repository.

**再次尝试 git push -u origin master**

<pre><code>Username for 'https://github.com': zxcbbn
Password for 'https://zxcbbn@github.com': 
To https://github.com/zxcbbn/pythoncamp0.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/zxcbbn/pythoncamp0.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
</code></pre>

尝试 git push -u gitbook +master

<pre><code>
Username for 'https://git.gitbook.com': zxcbbn
Password for 'https://zxcbbn@git.gitbook.com': 
remote: Forbidden
fatal: unable to access 'https://git.gitbook.com/zxcbbn/pythoncamp0.git/': The requested URL returned error: 403

</code></pre>

**无法解决问题，不知道下一步往哪方面找问题**
### update 3/21/2015 可以推送gitbook，但不能生成

<pre><code>
Tweaking book.json
Installing plugins
Install plugins in /tmp/book
Install plugin autocover from npm (gitbook-plugin-autocover) with version *
Install plugin mathjax from npm (gitbook-plugin-mathjax) with version *
gitbook-plugin-mathjax@0.0.6 node_modules/gitbook-plugin-mathjax
Successfully installed plugins!
Building Site, will upload
Starting build ...
Cannot read property 'text' of undefined
</code></pre>

**根据Cannot read property 'text' of undefined搜索**
得到 [TypeError: Cannot read property 'text' of undefined #135](https://github.com/GitbookIO/gitbook/issues/135)
尝试删除 summary 中的空行，git push -u gitbook成功

**备注**
网络环境：没有变化，使用 shadowsocks for Mac, Global Mode
操作系统：OS X Yosemite 10.10.2

**Comment by cp4** [comment]
用完整URL代替gitbook
